on:
  push:
    branches:
      - main

jobs:
  block_direct_push:
    runs-on: ubuntu-latest
    steps:
      - name: Block direct push
        run: |
          echo "::error::You cannot push to 'main' directly."
          echo "Please create a new branch and open a Pull Request instead."
          exit 1
